### ISSUE TITLE
Runtime error when using in React project

### ISSUE THREAD

**Issue by tkfischer** [smart-on-fhir/health-cards-validation-SDK#125]
Hi,

Followed the instructions on integrating the SDK programmatically to call "validate" on various QR artifacts but running into below error:

TypeError: Cannot read property 'signals' of undefined 

Further stack trace details below. Upon encountering this issue in my JS React project, I converted (just the essentials) it to TS and the tsconfig.json is straight from CRA.  It seems others have encountered this signals issue and I tried some tweaks reported elsewhere (such as commonjs, etc.) but not able to resolve.
Platform is MacOS 10.14.x Mojave with the Intel processor

Thanks.

**Comment by tkfischer** [comment]
Further stack trace below:

normalizeSignal
src/signals.js:28
  25 |   forced = false,
  26 |   standard,
  27 | }) {
> 28 |   const {
  29 |     signals: { [name]: constantSignal },

...
getSignals
src/signals.js:10
   8 | export const getSignals = function() {
   9 |   const realtimeSignals = getRealtimeSignals()

...
getSignalsByName
src/main.js:9

...
./node_modules/health-cards-validation-sdk/node_modules/human-signals/build/src/main.js
src/main.js:23

...

**Comment by jmandel** [comment]
Thanks for this report. Are you looking to run this code directly in the browser, as part of your compiled React app? (@ljoy913 may be able to comment -- I'm not sure whether in-browser usage is a supported scenario today.)

**Comment by tkfischer** [comment]
Yes, wanted to try that first to save cycles on server back and forth. Any reason it shouldn't work ?

**Comment by ljoy913** [comment]
Currently, running the sdk in the browser does not work. My initial attempts to bundle all the node dependencies has failed with cryptic errors at runtime and I haven't had the chance to track down the failing component(s).
So, for now, client-side react usage is not supported.  Sorry.

**Comment by tkfischer** [comment]
Got it. I'll close this issue then.

While you both are here, can you comment on compatibility with the QR code issued by California. I have one (issued on the CA state portal) and it doesn't seem to work. Errors out trying to get the numeric and jws string.  I need to look into it more, but it seemed to report some partial info correctly.

**Comment by jmandel** [comment]
Thanks -- let's keep this issue open until we add a FAQ note in the README to capture this

**Comment by jmandel** [comment]
> can you comment on compatibility with the QR code issued by California

California's implementation has been validated against this very SDK, and should support Health Cards in a totally spec-compliant way. If you're seeing specific errors with your QR, feel free to reach out to me on https://chat.fhir.org (send me a PM, or consider joining the `#smart/health-cards` channel) and we can track this down.

**Comment by ljoy913** [comment]
Try checking your CA-QR code at : https://demo-portals.smarthealth.cards/VerifierPortal.html
It uses this SDK for validation.

**Comment by tkfischer** [comment]
Works perfectly (on third attempt). Pulled the FHIR bundle, all info looks good. Cool. Super work.
