### ISSUE TITLE
Warn if QR uses unnecessary padding

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/health-cards-validation-SDK#127]
At
 https://github.com/smart-on-fhir/health-cards-validation-SDK/blob/989fcf374ab8575d89e881d281d8c30d7ad28fb0/src/image.ts#L124-L133

... we could add a check that re-encodes the QR and generates a warning if the re-encoded QR uses a smaller symbol that the original. For example, if we see a V18 or V22 symbol that *could have been encoded* as a V15 symbol, we'd add a warning.

**Comment by christianpaquin** [comment]
Could the error-correction level affect this? If I understand correctly, the spec doesn't prescribe an error-correction level, as long as the resulting QR is <v22. So in theory, an implementation could choose boost the ECC level to get a more resilient image, and still be within the valid version range. Did you see implementations that added extra padding (and where did this padding came from)?

**Comment by jmandel** [comment]
The error correction level could indeed affect this. At the *very least* we could perform this "sanity check" using the same error correction level that the original QR used (not sure if it's readily available). Or the warning/info could say "pass a minimum-ecc flag if you're intentionally setting a level of ...."

I should have mentioned in the original post: yes, this feature suggestion is motivated by a real-world issue (basically, an implementer following [this example](https://github.com/dvci/health-cards-walkthrough/issues/4) too closely)
