### ISSUE TITLE
Getting Key Import Error on Firefox

### ISSUE THREAD

**Issue by jdkizer9** [smart-on-fhir/health-cards-validation-SDK#130]
To reproduce:

- Using latest version of Firefox on macOS, add [example 0 JWS](https://spec.smarthealth.cards/examples/example-00-d-jws.txt) to the input field below "Decode Numeric" button
- After properly decoding the SHC and downloading the JWKS, the following error is shown:

Confirmed that this still works on Chrome, and IIRC worked previously on Firefox, so possibly a Firefox bug?

<img width="1579" alt="Screen Shot 2021-07-21 at 7 22 41 AM" src="https://user-images.githubusercontent.com/6721921/126495704-5e4b648f-2b8b-432e-a9b4-eee9a3716f2c.png">

<img width="329" alt="Screen Shot 2021-07-21 at 7 21 11 AM" src="https://user-images.githubusercontent.com/6721921/126495499-eac17013-447f-4bb8-af2b-232f7b764fb9.png">

**Comment by ljoy913** [comment]
I'm seeing the same on Firefox and have an update to fix it.

**Comment by ljoy913** [comment]
- Fixed with https://github.com/smart-on-fhir/health-cards-tests/pull/65
